export const LANGUAGES = {
    markdown: {
        id: 'markdown',
        monacoId: 'markdown',
        label: 'Markdown',
        extensions: ['.md', '.mdx'],
        icon: 'devicon-markdown-plain',
        color: '#083fa1',
    },
    javascript: {
        id: 'javascript',
        monacoId: 'javascript',
        label: 'JavaScript',
        extensions: ['.js', '.mjs', '.cjs'],
        icon: 'devicon-javascript-plain',
        color: '#f7df1e',
    },
    typescript: {
        id: 'typescript',
        monacoId: 'typescript',
        label: 'TypeScript',
        extensions: ['.ts', '.mts'],
        icon: 'devicon-typescript-plain',
        color: '#3178c6',
    },
    jsx: {
        id: 'jsx',
        monacoId: 'javascript',
        label: 'JSX',
        extensions: ['.jsx'],
        icon: 'devicon-react-original',
        color: '#61dafb',
    },
    tsx: {
        id: 'tsx',
        monacoId: 'typescript',
        label: 'TSX',
        extensions: ['.tsx'],
        icon: 'devicon-react-original',
        color: '#61dafb',
    },
    html: {
        id: 'html',
        monacoId: 'html',
        label: 'HTML',
        extensions: ['.html', '.htm'],
        icon: 'devicon-html5-plain',
        color: '#e34f26',
    },
    css: {
        id: 'css',
        monacoId: 'css',
        label: 'CSS',
        extensions: ['.css'],
        icon: 'devicon-css3-plain',
        color: '#1572b6',
    },
    scss: {
        id: 'scss',
        monacoId: 'scss',
        label: 'SCSS',
        extensions: ['.scss'],
        icon: 'devicon-sass-plain',
        color: '#c6538c',
    },
    json: {
        id: 'json',
        monacoId: 'json',
        label: 'JSON',
        extensions: ['.json'],
        icon: 'devicon-json-plain',
        color: '#292929',
    },
    yaml: {
        id: 'yaml',
        monacoId: 'yaml',
        label: 'YAML',
        extensions: ['.yaml', '.yml'],
        icon: 'devicon-yaml-plain',
        color: '#cb171e',
    },
    toml: {
        id: 'toml',
        monacoId: 'ini',
        label: 'TOML',
        extensions: ['.toml'],
        icon: null,
        color: '#9c4121',
    },
    python: {
        id: 'python',
        monacoId: 'python',
        label: 'Python',
        extensions: ['.py'],
        icon: 'devicon-python-plain',
        color: '#3776ab',
    },
    rust: {
        id: 'rust',
        monacoId: 'rust',
        label: 'Rust',
        extensions: ['.rs'],
        icon: 'devicon-rust-plain',
        color: '#dea584',
    },
    go: {
        id: 'go',
        monacoId: 'go',
        label: 'Go',
        extensions: ['.go'],
        icon: 'devicon-go-plain',
        color: '#00add8',
    },
    java: {
        id: 'java',
        monacoId: 'java',
        label: 'Java',
        extensions: ['.java'],
        icon: 'devicon-java-plain',
        color: '#ed8b00',
    },
    php: {
        id: 'php',
        monacoId: 'php',
        label: 'PHP',
        extensions: ['.php'],
        icon: 'devicon-php-plain',
        color: '#777bb4',
    },
    ruby: {
        id: 'ruby',
        monacoId: 'ruby',
        label: 'Ruby',
        extensions: ['.rb'],
        icon: 'devicon-ruby-plain',
        color: '#cc342d',
    },
    swift: {
        id: 'swift',
        monacoId: 'swift',
        label: 'Swift',
        extensions: ['.swift'],
        icon: 'devicon-swift-plain',
        color: '#f05138',
    },
    kotlin: {
        id: 'kotlin',
        monacoId: 'kotlin',
        label: 'Kotlin',
        extensions: ['.kt', '.kts'],
        icon: 'devicon-kotlin-plain',
        color: '#7f52ff',
    },
    bash: {
        id: 'bash',
        monacoId: 'shell',
        label: 'Bash',
        extensions: ['.sh', '.bash'],
        icon: 'devicon-bash-plain',
        color: '#4eaa25',
    },
    sql: {
        id: 'sql',
        monacoId: 'sql',
        label: 'SQL',
        extensions: ['.sql'],
        icon: 'devicon-azuresqldatabase-plain',
        color: '#d9272e',
    },
    graphql: {
        id: 'graphql',
        monacoId: 'graphql',
        label: 'GraphQL',
        extensions: ['.graphql', '.gql'],
        icon: 'devicon-graphql-plain',
        color: '#e10098',
    },
    dockerfile: {
        id: 'dockerfile',
        monacoId: 'dockerfile',
        label: 'Dockerfile',
        extensions: ['Dockerfile', '.dockerfile'],
        icon: 'devicon-docker-plain',
        color: '#2496ed',
    },
    xml: {
        id: 'xml',
        monacoId: 'xml',
        label: 'XML',
        extensions: ['.xml'],
        icon: 'devicon-xml-plain',
        color: '#fb8c00',
    },
    c: {
        id: 'c',
        monacoId: 'c',
        label: 'C',
        extensions: ['.c', '.h'],
        icon: 'devicon-c-plain',
        color: '#a8b9cc',
    },
    cpp: {
        id: 'cpp',
        monacoId: 'cpp',
        label: 'C++',
        extensions: ['.cpp', '.cxx', '.cc', '.hpp'],
        icon: 'devicon-cplusplus-plain',
        color: '#00599c',
    },
    csharp: {
        id: 'csharp',
        monacoId: 'csharp',
        label: 'C#',
        extensions: ['.cs'],
        icon: 'devicon-csharp-plain',
        color: '#239120',
    },
    csv: {
        id: 'csv',
        monacoId: 'csv',
        label: 'CSV',
        extensions: ['.csv'],
        icon: null,
        color: '#217346',
    },
    whatsapp: {
        id: 'whatsapp',
        monacoId: 'whatsapp',
        label: 'WhatsApp',
        extensions: ['.wachat'],
        icon: null,
        color: '#25d366',
    },
    plaintext: {
        id: 'plaintext',
        monacoId: 'plaintext',
        label: 'Plain Text',
        extensions: ['.txt'],
        icon: null,
        color: '#888888',
    },
};

export const LANGUAGE_LIST = Object.values(LANGUAGES);

export const getLanguage = id => LANGUAGES[id] ?? LANGUAGES.plaintext;

const MIME_TYPES = {
    markdown: 'text/markdown',
    javascript: 'text/javascript',
    typescript: 'application/typescript',
    jsx: 'text/jsx',
    tsx: 'text/tsx',
    html: 'text/html',
    css: 'text/css',
    scss: 'text/x-scss',
    json: 'application/json',
    yaml: 'application/yaml',
    toml: 'application/toml',
    python: 'text/x-python',
    rust: 'text/x-rustsrc',
    go: 'text/x-go',
    java: 'text/x-java-source',
    php: 'application/x-php',
    ruby: 'text/x-ruby',
    swift: 'text/x-swift',
    kotlin: 'text/x-kotlin',
    bash: 'application/x-sh',
    sql: 'application/sql',
    graphql: 'application/graphql',
    dockerfile: 'text/x-dockerfile',
    xml: 'application/xml',
    c: 'text/x-csrc',
    cpp: 'text/x-c++src',
    csharp: 'text/x-csharp',
    csv: 'text/csv',
    whatsapp: 'text/x-whatsapp',
    plaintext: 'text/plain',
};

export const getMimeType = id => MIME_TYPES[id] ?? 'text/plain';

export const getLanguageByFilename = filename => {
    if (!filename) return LANGUAGES.plaintext;
    const lower = filename.toLowerCase();
    const dotIndex = lower.lastIndexOf('.');
    const ext = dotIndex !== -1 ? lower.slice(dotIndex) : lower;

    for (const lang of LANGUAGE_LIST) {
        if (lang.extensions.some(e => e.toLowerCase() === ext)) return lang;
    }
    return LANGUAGES.plaintext;
};
