export const TIPS = [
    {
        id: 'instant-collaboration',
        icon: 'zap',
        title: 'Instant collaboration',
        body: 'Share the URL — anyone with the link can edit in real time, no sign-up required.',
        color: '#6366f1',
    },
    {
        id: 'multiple-files',
        icon: 'files',
        title: 'Multiple files',
        body: 'Use the {{icon:plus}} button in the tab bar to add files. Each file can have its own language.',
        color: '#0ea5e9',
    },
    {
        id: 'run-your-code',
        icon: 'terminal',
        title: 'Run your code',
        body: 'JS, HTML, Markdown and more have live runners. Click the play button in the status bar.',
        color: '#10b981',
    },
    {
        id: 'command-palette',
        icon: 'keyboard',
        title: 'Command palette',
        body: 'Press {{shortcut:command_palette}} to open the command palette and access all actions quickly.',
        color: '#f59e0b',
    },
    {
        id: 'fork-any-bin',
        icon: 'git-fork',
        title: 'Fork any bin',
        body: 'Found something interesting? Hit Fork to get your own editable copy instantly.',
        color: '#ec4899',
    },
    {
        id: 'ai-completions',
        icon: 'bot',
        title: 'AI completions',
        body: 'Connect your own API key in Settings to enable inline AI completions in the editor.',
        color: '#8b5cf6',
    },
    {
        id: 'embed-anywhere',
        icon: 'link',
        title: 'Embed anywhere',
        body: 'Every bin has an embed URL — drop it in any page for a read-only syntax-highlighted view.',
        color: '#14b8a6',
    },
    {
        id: 'your-keys-your-data',
        icon: 'shield',
        title: 'Your keys, your data',
        body: "API keys never leave your device. Everything is stored in your browser's localStorage.",
        color: '#f97316',
    },
];
